Repository hmcts/ts-translation-service, pull requests merged in 2022-12, with the labels that each got.

#140 WLTS-58: Check CVEs showing on ts-translation-service
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-140

#148 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-148

#149 WLTS-59 CVE-2021-37533 Suppression
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-149

#153 WLTS-61 Upgrade base charts for Jenkins enhancements - bumped java ve…
  charts/ts-translation-service/Chart.yaml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-153
