Repository hmcts/ts-translation-service, pull requests merged in 2022-11, with the labels that each got.

#127 WLTS-52 CVE-2022-31690, CVE-2022-31690 WLTS-53 CVE-2022-42252 Suppres…
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-127

#134 WLTS-57-CVE-2022-41854-Suppression
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-134

#102 WLTS: Fix CVEs for which we have a solution in CCD.
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-102
