Repository hmcts/ts-translation-service, pull requests merged in 2023-11, with the labels that each got.

#259 CCD-4771 : Fix CVE-2023-35116
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-259

#263 HMAN-602 : Add retries to all acb.tpl.yaml entries
  acb.tpl.yaml
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-263

#264 Fix retries issues
  acb.tpl.yaml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-264
