Repository hmcts/ts-translation-service, pull requests merged in 2023-05, with the labels that each got.

#189 WLTS-67 Upgrade dependencies to resolve CVE-2023-24998
  Dockerfile
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-189

#212 WLTS-71 : fix for various CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-212

#215 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-215
