Repository hmcts/ts-translation-service, pull requests merged in 2024-02, with the labels that each got.

#270 Attempt to fix ApplicationInsights
  .gitignore
  Dockerfile
  build.gradle
  charts/ts-translation-service/Chart.yaml
  charts/ts-translation-service/values.preview.template.yaml
  charts/ts-translation-service/values.yaml
  infrastructure/app-insights.tf
  lib/applicationinsights.json
Labels: ns:ts, prd:ts, add-or-update, rel:ts-translation-service-pr-270

#274 Remove unneeded secret entry
  infrastructure/app-insights.tf
Labels: ns:ts, prd:ts, no-changes, rel:ts-translation-service-pr-274

#272 Adding conditional count, delete all envs bar prod
  infrastructure/main.tf
Labels: ns:ts, prd:ts, destroy, rel:ts-translation-service-pr-272

#275 Adding prevent deletion flag to false
  infrastructure/main.tf
Labels: ns:ts, prd:ts, destroy, rel:ts-translation-service-pr-275

#279 Update .terraform-version
  infrastructure/.terraform-version
Labels: ns:ts, prd:ts, add-or-update, rel:ts-translation-service-pr-279

#280 Update v15 db config after migration on all environments including Prod
  charts/ts-translation-service/Chart.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:ts, prd:ts, destroy, rel:ts-translation-service-pr-280

#269 CCD-4969: bumped spring-security.version to v5.8.5
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, destroy, rel:ts-translation-service-pr-269
