Repository hmcts/ts-translation-service, pull requests merged in 2024-10, with the labels that each got.

#310 CCD-5193 : Fix : CVE-2022-45047
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-310

#300 CCD-5158 Fix CVE-2023-46589
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-300

#311 CCD-5925-Tidy-Suppressions
  config/owasp/suppressions.xml
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-311

#313 CME-48 Java 21 update
  .github/workflows/dependency-check.yml
  .github/workflows/swagger.yml
  Dockerfile
  README.md
  acb.tpl.yaml
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/integrationTest/resources/application-itest.yml
  src/test/java/uk/gov/hmcts/reform/translate/errorhandling/RestExceptionHandlerTest.java
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-313
