Repository hmcts/ts-translation-service, pull requests merged in 2025-06, with the labels that each got.

#333 CCD-6379 Configure Renovate
  .github/renovate.json
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-333

#336 CME-679 Replace JitPack with Azure Artifacts
  build.gradle
  settings.gradle
Labels: ns:ts, prd:ts, rel:ts-translation-service-pr-336

#350 CCD-6268 :: added Ft's for swagger testing
  .github/workflows/swagger.yml
  src/functionalTest/java/uk/gov/hmcts/reform/translate/TranslationServiceTestAutomationAdapter.java
  src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/F-125.feature
  src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/F-125_Test_Swagger_JSON_Base_Data.td.json
  src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/F-125_Test_Swagger_UI_Base_Data.td.json
  src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/S-125.1.td.json
  src/functionalTest/resources/features/F-125 - Swagger Pages and API Specs/S-125.2.td.json
  src/main/resources/application.yaml
Labels: ns:ts, prd:ts, keep-helm, enable_keep_helm, rel:ts-translation-service-pr-350
